### PR TITLE
Update to sjs-dom 2.0.0

### PR DESCRIPTION
**Pull request by armanbilge**
Supersedes #30.

### CODE REVIEW

**Comment by djspiewak** [comment]
@sjrd I'm assuming this means we need to bump to 2.0.0 here?

**Comment by armanbilge** [comment]
No, this is only a test dependency :)

**Comment by djspiewak** [comment]
Oh, whew!

**Comment by sjrd** [comment]
If it hadn't just been a test dependency, I wouldn't have let you introduce that dependency at all when I first reviewed. 😉

**Pull request merged**
